[tool.poetry]
name = "sem-desc-curator"
version = "1.2.0"
description = "UI for browsing/editing semantic descriptions"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
packages = [
    { include = "smc" }
]

[tool.poetry.scripts]
smc = 'smc.cli:cli'

[tool.poetry.dependencies]
python = "^3.8"
kgdata = "~1.6.0"
sm-grams = "~1.4.0"
sem-desc = "~3.0.0"
peewee = "^3.14.4"
Flask = "^2.0.2"
python-dotenv = ">=0.19.0"
tornado = "^6.1"
flask-peewee-restful = "^1.0.6"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
