[tool.poetry]
name = "sem-desc-curator"
version = "0.1.0"
description = "UI for browsing/editing semantic descriptions"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
packages = [
    { include = "smc" }
]

[tool.poetry.scripts]
smc = 'smc.cli:cli'

[tool.poetry.dependencies]
python = "^3.8"
kgdata = "^1.2.3"
sem-desc = "^0.1.15"
peewee = "^3.14.4"
Flask = "^2.0.1"
python-dotenv = "^0.19.0"
tornado = "^6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
